// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB_Fv4Z9acSTYuvwL_v1Goiega2BTHAVKc',
    appId: '1:421930980911:web:16d76eb348b87fa57f98da',
    messagingSenderId: '421930980911',
    projectId: 'digital-portobello',
    authDomain: 'digital-portobello.firebaseapp.com',
    storageBucket: 'digital-portobello.appspot.com',
    measurementId: 'G-R707HY6BBG',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAZuOx_ez__8QBL-V58nrR0SPGtfi_ZnH0',
    appId: '1:421930980911:android:c5208128f74bfa2c7f98da',
    messagingSenderId: '421930980911',
    projectId: 'digital-portobello',
    storageBucket: 'digital-portobello.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD5CIJbGLIw2f5cGUOJ8QfQnjt_df1YEEU',
    appId: '1:421930980911:ios:25938fe59caa32387f98da',
    messagingSenderId: '421930980911',
    projectId: 'digital-portobello',
    storageBucket: 'digital-portobello.appspot.com',
    iosClientId:
        '421930980911-ve3bkqngjfqjkh3pvs5p6um292spmqd2.apps.googleusercontent.com',
    iosBundleId: 'com.example.digitalPortobello',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD5CIJbGLIw2f5cGUOJ8QfQnjt_df1YEEU',
    appId: '1:421930980911:ios:25938fe59caa32387f98da',
    messagingSenderId: '421930980911',
    projectId: 'digital-portobello',
    storageBucket: 'digital-portobello.appspot.com',
    iosClientId:
        '421930980911-ve3bkqngjfqjkh3pvs5p6um292spmqd2.apps.googleusercontent.com',
    iosBundleId: 'com.example.digitalPortobello',
  );
}
